export const STORIES_ACTIONS = {
  REMOVE_STORY: 'REMOVE_STORY',
  STORIES_FETCH_INIT: 'STORIES_FETCH_INIT',
  STORIES_FETCH_FAILURE: 'STORIES_FETCH_FAILURE',
  STORIES_FETCH_SUCCESS: 'STORIES_FETCH_SUCCESS',
};
